[add] taskモデルのモデルスペックの作成、テストデータの作成
olive-2424/sample_app_for_rspec pull request #2
Opened 2021-01-06 15:18 UTC by olive-2424

実装内容
・taskモデルのモデルスペックの作成、taskモデルのバリデーションのテストコードを記載
・factoryを使ったテストデータの作成
確認方法
`models/task_spec.rb`に
・taskモデルの全ての属性があれば有効であること
・titleがなければ無効であること
・statusがなければ無効であること
・titleが重複する場合無効であること
・titleが重複しない場有効であること
これらをexampleとして記載
また、taskモデルのバリデーション部分のコードをコメントアウト、または、マッチャを`to_not`にした場合、エラーが発生することを確認
<img width="624" alt="model_spec_error" src="https://user-images.githubusercontent.com/62058482/103783638-53fa2000-507c-11eb-9cf4-6820e42485c7.png">
factories/user.rb
ユーザーテストデータのemail、タスクテストデータのtitleにシーケンスでデータを重複しないように作成

2021-01-07 14:49 UTC, olive-2424 commented
修正内容確認
・ ea59b853d5593517a488e0d13feca9352a3033a8 でタスクのテストデータにdeadline属性を追加しました
・ 33b699a3948080bdd7ee2b387fe2bdaebe7d94a4 でモデルスペックの変数名を役割がわかるように変更しました
・ 8707f3f821554328879a3b413440d4bf667f8f77 でバリデーションの有効性についてのテストコードを`be_valid,be_invalid`とマッチャを使った記述に変更しました
・ 99afbd4acef0bbdecb9ee830ead0d4cc4373bd78 でモデルスペックで`FactoryBot`の記述を省略できるように変更しました
疑問点確認
・解答例だとエラーメッセージの確認のマッチャを`to eq`を使っていますが、`to include`どちらでも良いのか？
・taskインスタンスが有効だった場合のexmapleにおいて、解答例だと最後に`expect(task.errors).to be_empty`はその前のコードの`to be_valid`で有効性が確かめられているので、エラーメッセージの存在を確認する必要がなぜあるのか疑問に思いました。
他の人が読んだときに他のバリデーションに関するexampleにおいてもエラーメッセージを確認しているので、統一してバリデーションに関するテストはエラーメッセージの確認をすることで、可読性を上げるということでしょうか？
長文すみません、確認よろしくお願いします！！

2021-01-08 04:14 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status   { 'todo' }
enumの形式で記載するようにしましょう
```suggestion
    status   { :todo }
```

2021-01-08 04:24 UTC, yuji91 commented on spec/models/task_spec.rb
> +    end
itとendの間は改行した方が見やすいかもしれないです。

2021-01-08 04:24 UTC, yuji91 requested changes
細かいですが2点指摘しました！

2021-01-08 08:50 UTC, olive-2424 commented on spec/factories/tasks.rb
> +    status   { 'todo' }
60d43adf5fe1847754d7be77c16f6b652ae3c6e1 で修正しました

2021-01-08 08:50 UTC, olive-2424 commented on spec/models/task_spec.rb
> +    end
0a37bda50fc287ad6a0760622b0cea35718ba6cc で修正しました

2021-01-08 10:19 UTC, yuji91 approved these changes

2021-01-08 10:28 UTC, merged